name: Demo pipeline

on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches: [main, dev]
    # schedule:
    #     - cron:  "*/1 * * * *"

jobs:

    setup_job:
        runs-on: ubuntu-latest #we can have macos-latest, windows-latest. all default github action runners
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: create file
              run: |
                touch github-action.txt
                ls -la
                echo Hello world
                cat README.md
    build_job:
        needs: 
            - setup_job

        runs-on: ubuntu-latest
        steps:
            - name: display hello
              run: echo hello
            - name: Display github action.txt
              run: cat github-action.txt
    deploy_job:
        needs: setup_job
        runs-on: macos-latest
        steps: 
            - run: echo hello mac
        
